image: maven:3.6-jdk-11

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -C -B -U -s settings.xml install -DskipTests=true -P Development
    - step:
        name: Deploy to Development
        deployment: Development
        trigger: manual
        caches:
          - maven
        script:
          - mvn -B -U -s settings.xml deploy -DskipTests=true -P Development
    - step:
       name: Deploy to Staging
       deployment: Staging
       trigger: manual
       caches:
          - maven
       script:
         - mvn -B -U -s settings.xml deploy -DskipTests=true -P Staging
    - step:
       name: Deploy to Production
       deployment: Production
       trigger: manual
       caches:
          - maven
       script:
         - mvn -B -U -s settings.xml deploy -DskipTests=true -P Production
