image: maven:3.6-jdk-11

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B -U -s settings.xml deploy -DskipTests=true
#          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"Space1889_Plugin/target/space1889-2.0.0-SNAPSHOT.jar"
#     - step:
#         name: Deploy to Development
#         deployment: Development
#         caches:
#           - maven
#         script:
#           - mvn -B -U -s settings.xml deploy -DskipTests=true -P Development
#     - step:
#        name: Deploy to Staging
#        deployment: Staging
#        trigger: manual
#        caches:
#           - maven
#        script:
#          - mvn -B -U -s settings.xml deploy -DskipTests=true -P Staging
#     - step:
#        name: Deploy to Production
#        deployment: Production
#        trigger: manual
#        caches:
#           - maven
#        script:
#          - mvn -B -U -s settings.xml deploy -DskipTests=true -P Production
