<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

   <parent>
      <groupId>de.rpgframework</groupId>
      <artifactId>rpgframework-common</artifactId>
      <version>1.0</version>
   </parent>

	<groupId>de.rpgframework</groupId>
	<artifactId>splittermond-master</artifactId>
	<version>1.0</version>
	<name>Splittermond Master Build</name>
	<packaging>pom</packaging>

	<modules>
      <module>Splittermond_BBCode</module>
      <module>Splittermond_Beastmaster</module>
      <module>Splittermond_BuU</module>
      <module>Splittermond_CharGen</module>
      <module>Splittermond_CharGen_JFX</module>
      <module>Splittermond_Core</module>
	</modules>
</project>
