<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.prelle.rpgframework</groupId>
    <artifactId>splittermond-all</artifactId>
    <version>4.0.0-SNAPSHOT</version>
  </parent>

	<artifactId>splittermond-bbcode</artifactId>
	<name>Splittermond_BBCode</name>
	<description>Splittermond print to BBCode</description>

	<developers>
		<developer>
			<name>Frank Büttner</name>
			<email>frank.buettner@posteo.de</email>
			<timezone>GMT+1</timezone>
			<roles>
				<role>Lead developer</role>
			</roles>
		</developer>
		<developer>
			<name>Stefan Prelle</name>
			<email>stefan@rpgframework.de</email>
			<timezone>GMT+1</timezone>
			<roles>
				<role>Maintainer</role>
			</roles>
		</developer>
	</developers>

	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-api</artifactId>
            <version>[3.0.0-SNAPSHOT, 3.99.99)</version>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-core</artifactId>
			<version>[3.0.0-SNAPSHOT, 3.99.99)</version>
		</dependency>
	</dependencies>
</project>