<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.rpgframework</groupId>
    <artifactId>rpgframework-root</artifactId>
    <version>3.0.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <groupId>org.prelle.rpgframework</groupId>
  <artifactId>splittermond-chargen</artifactId>
  <version>2.2.0</version>
  <name>Splittermond_CharGen</name>
  <description>Splittermond Character Generator </description>

  <dependencies>
  	<dependency>
  		<groupId>log4j</groupId>
  		<artifactId>log4j</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>de.rpgframework</groupId>
  		<artifactId>rpgframework-api</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-core</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-msk</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-beastmaster</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-buu</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle</groupId>
  		<artifactId>babylon</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-selenia</artifactId>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-world</artifactId>
  		<scope>test</scope>
  	</dependency>
  </dependencies>
</project>