<project xmlns="http://maven.apache.org/POM/4.0.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <parent>
      <groupId>de.rpgframework</groupId>
      <artifactId>splittermond-common</artifactId>
      <version>1.0</version>
      <relativePath>../common.xml</relativePath>
   </parent>

  <groupId>org.prelle.rpgframework</groupId>
  <artifactId>splittermond-jdg</artifactId>
  <version>1.3.0</version>
  <name>Splittermond 'Jenseits der Grenzen'</name>
  <description>Splittermond supplement 'Jenseits der Grenzen' </description>

  <dependencies>
  	<dependency>
  		<groupId>log4j</groupId>
  		<artifactId>log4j</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
   		<scope>test</scope>
  	</dependency>
  	<dependency>
  		<groupId>de.rpgframework</groupId>
  		<artifactId>rpgframework-api</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-core</artifactId>
  	</dependency>
  </dependencies>
</project>