<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.prelle.rpgframework</groupId>
		<artifactId>splittermond-all</artifactId>
		<version>4.2.0-SNAPSHOT</version>
	</parent>

	<artifactId>splittermond-plugin</artifactId>
	<name>Splittermond</name>
	<version>4.4.1</version>

	<properties>
		<maven.install.skip>false</maven.install.skip>
		<maven.deploy.skip>true</maven.deploy.skip>
	</properties>

	<licenses>
		<license>
			<name>LGPL</name>
		</license>
	</licenses>

	<dependencies>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-chargen</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-chargen-jfx</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-data</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>src/main/assembly.xml</descriptor>
					</descriptors>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<useUniqueVersions>false</useUniqueVersions>
							<packageName>SPLITTERMOND</packageName>
						</manifest>
						<manifestEntries>
							<UUID>43f97ab7-1f2e-4fa2-a538-32f8878be56a</UUID>
							<Url>https://www.rpgframework.de/</Url>
							<Bugtracker>https://rpgframework.atlassian.net/servicedesk/customer/portals</Bugtracker>
							<State>STABLE</State>
							<Build-Time>${maven.build.timestamp}</Build-Time>
							<MinVersion>4.1.0-SNAPSHOT</MinVersion>
							<MaxVersion>4.99.99</MaxVersion>
							<Provides>CORE</Provides>
						</manifestEntries>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id> <!-- this is used for inheritance merges -->
						<phase>package</phase> <!-- bind to the packaging phase -->
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>scp</id>
						<phase>deploy</phase>
						<configuration>
							<tasks>
								<echo message="Unpack manifest from jar" />
								<unzip
									src="target/${project.artifactId}-${project.version}.jar"
									dest="target">
									<patternset>
										<include name="META-INF/MANIFEST.MF" />
									</patternset>
								</unzip>
								<copy file="target/META-INF/MANIFEST.MF"
									tofile="target/${project.artifactId}-${project.version}.mf" />

								<echo
									message="Copy plugin descriptor ${project.artifactId}-${project.version}.mf to ${deploymentServer}:${deploymentPath}" />
								<scp
									todir="${BB_USER_TOKEN}:${BB_PWD_TOKEN}@${deploymentServer}:${deploymentPath}/"
									sftp="true" failonerror="true" trust="true" verbose="false">
									<fileset dir="target">
										<include
											name="${project.artifactId}-${project.version}.mf" />
									</fileset>
								</scp>
								<echo
									message="Copy plugin to ${deploymentServer}:${deploymentPath}" />
								<scp
									todir="${BB_USER_TOKEN}:${BB_PWD_TOKEN}@${deploymentServer}:${deploymentPath}"
									sftp="true" failonerror="true" trust="true" verbose="false">
									<fileset dir="target">
										<include
											name="${project.artifactId}-${project.version}.jar" />
									</fileset>
								</scp>
							</tasks>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.apache.ant</groupId>
						<artifactId>ant-jsch</artifactId>
						<version>1.9.4</version>
					</dependency>
				</dependencies>
			</plugin>
			<!-- <plugin> -->
			<!-- <groupId>org.codehaus.mojo</groupId> -->
			<!-- <artifactId>wagon-maven-plugin</artifactId> -->
			<!-- <version>2.0.0</version> -->
			<!-- <executions> -->
			<!-- <execution> -->
			<!-- <id>deploy-plugin</id> -->
			<!-- <phase>deploy</phase> -->
			<!-- <goals> -->
			<!-- <goal>upload</goal> -->
			<!-- </goals> -->
			<!-- <configuration> -->
			<!-- <fromDir>target/</fromDir> -->
			<!-- <includes>*plugin.jar</includes> -->
			<!-- <url>scp://prelle@${deploymentServer}/</url> -->
			<!-- <toDir>${deploymentPath}</toDir> -->
			<!-- <targetId>rpgframework</targetId> -->
			<!-- </configuration> -->
			<!-- </execution> -->
			<!-- </executions> -->
			<!-- </plugin> -->
		</plugins>
	</build>
</project>