
alert.cancel_creation.title=Charactererzeugung abbrechen?
alert.cancel_creation.message=Das Zurückgehen wird die Charaktererschaffung abbrechen. Sämtlicher Fortschritt geht verloren!\n\nWirklich abbrechen?

alert.save_character.title=Änderungen speichern?
alert.save_character.message=Wollen Sie ihre Änderungen speichern?

command.primary.print=Drucken
command.primary.delete=Löschen

label.derived_values=Abgeleitete Werte
label.ep.free=EP
label.ep.total=Gesamt-EP
label.ep.used=eingesetzte EP
label.experience.short=EP



label.itemdata.basic=Grunddaten
label.itemdata.weapon=Nahkampf
label.itemdata.ranged=Fernkampf
label.itemdata.shield=Schild
label.itemdata.armor=Rüstung
label.itemdata.descr=Beschreibung
label.material=Material
label.personalization.first=Personalisierung
label.personalization.second=2. Personalisierung



label.level=Heldengrad
label.modified.short=mod.
label.name=Name
label.start=Start
label.value=Wert


navItem.overview=Grunddaten
navItem.powers=Stärken &\n Schwächen
navItem.skills=Fertigkeiten
navItem.spells=Zauber
navItem.resources=Ressourcen &\n Begleiter
navItem.gear=Ausrüstung
navItem.develop=Steigern

section.basedata=Basisdaten
section.appearance=Aussehen u.a.
section.attr.primary=Attribute
section.attr.secondary=Abgeleitete Werte

section.powers=Stärken
section.flaws=Schwächen
section.languages=Sprachen
section.culturelores=Kulturkunden

section.skill.normal=Allgemeine Fertigkeiten
section.skill.combat=Kampffertigkeiten
section.skill.magic=Magieschulen
section.schools=Zauberschulen
section.spells=Zauber
section.specializations=Schwerpunkte

section.resources=Ressourcen
section.companions=Kreaturen & Gefolge

spellslider.state1=inaktiv
spellslider.state2=gratis
spellslider.state3=EP-Kauf

specialization.sort.label=Spezialisierungen-Sortierung
specialization.sort.active_spells=Für gelernte Zauber
specialization.sort.all_spells=Für alle Zauber
specialization.sort.alphabet=Alphabetisch
