
alert.cancel_creation.title=Charactererzeugung abbrechen?
alert.cancel_creation.message=Das Zurückgehen wird die Charaktererschaffung abbrechen. Sämtlicher Fortschritt geht verloren!\n\nWirklich abbrechen?

alert.save_character.title=Änderungen speichern?
alert.save_character.message=Wollen Sie ihre Änderungen speichern?

command.primary.print=Drucken
command.primary.delete=Löschen

label.derived_values=Abgeleitete Werte
label.ep.free=EP
label.ep.total=Gesamt-EP
label.ep.used=eingesetzte EP
label.experience.short=EP
label.level=Heldengrad
label.modified.short=mod.
label.name=Name
label.start=Start
label.value=Wert

navItem.overview=Grunddaten
navItem.powers=Stärken & Schwächen
navItem.skills=Fertigkeiten

section.basedata=Basisdaten
section.appearance=Aussehen u.a.
section.attr.primary=Attribute
section.attr.secondary=Abgeleitete Werte

section.powers=Stärken
section.flaws=Schwächen
section.languages=Sprachen
section.culturelores=Kulturkunden

section.skill.normal=Allgemeine Fertigkeiten
section.skill.combat=Kampffertigkeiten
section.skill.magic=Magieschulen