<project xmlns="http://maven.apache.org/POM/4.0.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <parent>
      <groupId>de.rpgframework</groupId>
      <artifactId>splittermond-common</artifactId>
      <version>1.0</version>
      <relativePath>../common.xml</relativePath>
   </parent>

  <groupId>org.prelle.rpgframework</groupId>
  <artifactId>splittermond-idexport</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <name>Splittermond ID Export</name>
  <description>Exports all IDs used for Splittermond</description>

  <dependencies>
    <dependency>
  	  <groupId>log4j</groupId>
  	  <artifactId>log4j</artifactId>
  	  <version>1.2.17</version>
    </dependency>
    <dependency>
    	<groupId>de.rpgframework</groupId>
    	<artifactId>rpgframework-api</artifactId>
    	<version>0.9.2</version>
    </dependency>
    <dependency>
  	<groupId>org.prelle</groupId>
  	<artifactId>babylon</artifactId>
  	<version>0.9.2</version>
  	<scope>runtime</scope>
    </dependency>
  	<dependency>
  		<groupId>com.sun.mail</groupId>
  		<artifactId>javax.mail</artifactId>
  		<version>1.6.0-rc2</version>
  	  <scope>runtime</scope>
  	</dependency>
    <dependency>
  	  <groupId>org.prelle.rpgframework</groupId>
  	  <artifactId>splittermond-world</artifactId>
  	  <version>[1.0.7,)</version>
  	  <scope>runtime</scope>
    </dependency>
    <dependency>
  	  <groupId>org.prelle.rpgframework</groupId>
  	  <artifactId>splittermond-msk</artifactId>
  	  <version>[2.1.1,)</version>
  	  <scope>runtime</scope>
    </dependency>
    <dependency>
  	  <groupId>org.prelle.rpgframework</groupId>
  	  <artifactId>splittermond-buu</artifactId>
  	  <version>[0.2.0,)</version>
  	  <scope>runtime</scope>
    </dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-jdg</artifactId>
  		<version>[1.1.1,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-selenia</artifactId>
  		<version>[1.1.1,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-zhouijang</artifactId>
  		<version>[1.0.0,)</version>
  		<scope>runtime</scope>
  	</dependency>
   <dependency>
      <groupId>org.prelle.rpgframework</groupId>
      <artifactId>splittermond-farukan</artifactId>
      <version>[1.0.0,)</version>
      <scope>runtime</scope>
   </dependency>
   <dependency>
      <groupId>org.prelle.rpgframework</groupId>
      <artifactId>splittermond-fahrendevoelker</artifactId>
      <version>[1.0.0,)</version>
      <scope>runtime</scope>
   </dependency>
   <dependency>
      <groupId>org.prelle.rpgframework</groupId>
      <artifactId>splittermond-flammensenke</artifactId>
      <version>[1.1.0,)</version>
      <scope>runtime</scope>
   </dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-goetter</artifactId>
  		<version>[1.0.1,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-print</artifactId>
  		<version>[1.0.7,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-surmakar</artifactId>
  		<version>[1.1.1,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-beastmaster</artifactId>
  		<version>[0.1.0-SNAPSHOT,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-unreich</artifactId>
  		<version>[1.0.0,)</version>
  		<scope>runtime</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-core</artifactId>
  		<version>2.3.1</version>
  	</dependency>
  </dependencies>
  
  <build>
    <extensions>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-ssh</artifactId>
        <version>2.12</version>
      </extension>
    </extensions> 

    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      
      <!-- Packaging -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.0.2</version>
        <configuration>
          <archive>
          <manifest>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              <addClasspath>true</addClasspath>
              <mainClass>org.prelle.genesis.Genesis3Main</mainClass>
            </manifest>
            <manifestEntries>
              <Build-Info>${maven.build.timestamp} using Java ${java.version} on ${os.name}</Build-Info>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>

    </plugins>
  </build>
  
  <ciManagement>
  	<system>Bamboo</system>
  	<url>http://build.rgpframework.de/</url>
  </ciManagement>
  <issueManagement>
  	<system>JIRA</system>
  	<url>http://jira.rpgframework.de:18080/</url>
  </issueManagement>
  <scm>
    <url>http://git.rpgframework.de:7990</url>
    <developerConnection>scm:git:http://git.rpgframework.de:7990/scm/rpgfw/rpgframework_apis.git</developerConnection>
  </scm>
  <distributionManagement>
    <snapshotRepository>
        <id>snapshots</id>
        <name>rpgframeworkde-snapshots</name>
        <url>http://repository.rpgframework.de:8081/artifactory/libs-snapshot-local</url>
    </snapshotRepository>
    <repository>
        <id>central</id>
        <name>rpgframeworkde-releases</name>
        <url>http://repository.rpgframework.de:8081/artifactory/libs-release-local</url>
    </repository>
  </distributionManagement>
</project>