<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.rpgframework</groupId>
		<artifactId>splittermond-common</artifactId>
		<version>1.0</version>
		<relativePath>../common.xml</relativePath>
	</parent>

	<groupId>org.prelle.rpgframework</groupId>
	<artifactId>splittermond-idexport</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<name>Splittermond ID Export</name>
	<description>Exports all IDs used for Splittermond</description>

	<dependencies>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-api</artifactId>
		</dependency>
		<dependency>
         <groupId>de.rpgframework</groupId>
			<artifactId>babylon</artifactId>
			<version>2.0-SNAPSHOT</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>1.6.0-rc2</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-world</artifactId>
			<version>[1.0.7,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-msk</artifactId>
			<version>[2.1.1,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-buu</artifactId>
			<version>[0.4.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-jdg</artifactId>
			<version>[1.1.1,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-selenia</artifactId>
			<version>[1.1.1,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-zhouijang</artifactId>
			<version>[1.0.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-farukan</artifactId>
			<version>[1.0.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-fahrendevoelker</artifactId>
			<version>[1.0.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-flammensenke</artifactId>
			<version>[1.1.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-goetter</artifactId>
			<version>[1.0.1,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-print</artifactId>
			<version>[1.0.7,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-surmakar</artifactId>
			<version>[1.1.1,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-beastmaster</artifactId>
			<version>[0.1.0-SNAPSHOT,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-unreich</artifactId>
			<version>[1.0.0,)</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-core</artifactId>
		</dependency>
	</dependencies>
</project>