<?xml version="1.0" encoding="UTF-8"?>
<project name="splittermond-core" default="jar" basedir=".">
	<property name="build.src.dir"      value="src/main/java"/>
	<property name="build.classes.dir"  value="target/classes"/>
	<property name="build.dist.dir"     value="dist"/>
	<property name="package" value="splittermond-core"/>
	<property name="baseversion" value="2.0"/>
	<property name="version" value="${baseversion}"/>
    <property name="archivefile"    value="${package}.jar"/>
    <property name="sourcefile"     value="${package}-src.zip"/>
    <property name="javadocfile"    value="${package}-javadoc.zip"/>
    <property name="repository"     value="roleplaying"/>

	<path id="CLASSPATH">
		<pathelement location="libs/log4j.jar"/>
		<pathelement location="libs/javax.mail.jar"/>
	    <pathelement location="../RPGFramework_API/dist/rpgframework-api.jar"/>
	    <pathelement location="../Babylon_API/dist/babylon-api.jar"/>
	    <pathelement location="../SimplePersist/dist/simple-persist.jar"/>
	</path>

    <target name="clean" description="clean up" >
		<delete dir="${build.classes.dir}"/>
		<delete dir="${build.dist.dir}"/>
   </target>

	<target name="compile" depends="clean">
	    <mkdir dir="${build.classes.dir}"/>
	    <mkdir dir="${build.dist.dir}"/>
		<javac srcdir="${build.src.dir}" destdir="${build.classes.dir}" classpathref="CLASSPATH" includeantruntime="false" deprecation="on" debug="on" debuglevel="source,lines" />
	</target>

    <target name="jar" description="Generates the archive">
 		<jar destfile="${build.dist.dir}/${archivefile}">
		    <fileset dir="${build.classes.dir}" includes="**/*.class" excludes="foo/**/*.class" />
		    <fileset dir="src/main/resources" includes="data/**/*.xml" />
		    <fileset dir="src/main/resources" includes="i18n/**/*.properties i18n/**/*.html" />

 			<manifest>
      			<attribute name="Built-By" value="${user.name}"/>
      	     	<attribute name="Implementation-Title"   value="Splittermond Core Rules"/>
      	      	<attribute name="Implementation-Version" value="${version}"/>
      	      	<attribute name="Implementation-Vendor"  value="Stefan Prelle"/>
      		</manifest>
        	<service type="de.rpgframework.RulePlugin" provider="org.prelle.rpgframework.splittermond.SplittermondRules"/>
		</jar>
    	<copy file="${build.dist.dir}/${archivefile}" todir="export-libs"/>
 	</target>

    <target name="javadoc">
    	<javadoc
    		classpathref="CLASSPATH"
    		destdir="${build.dist.dir}/javadoc"
    	    author="true"
    	    version="true"
    	    use="true"
    	    windowtitle="Splittermond Core Rules Build ${version}">

    	    <packageset dir="${build.src.dir}" defaultexcludes="yes">
    	      <include name="org/prelle/**"/>
    	    </packageset>

    		<group title="Splittermond Core Rules" packages="org.prelle.splimo*"/>
    		<group title="Splittermond Core Rules - RPGFramework Adapter" packages="org.prelle.rpgframework.splittermond*"/>

    	    <bottom><![CDATA[<i>Copyright &#169; 2015-2017 Stefan Prelle</i>]]></bottom>
    	    <link href="http://docs.oracle.com/javase/8/docs/api/" />
    	    <link href="http://www.rpgframework.de/javadoc/rpgframework-api/" />
    	    <link href="http://www.rpgframework.de/javadoc/babylon-api/" />
    	    <link href="http://www.rpgframework.de/javadoc/simple-persist/" />
    	  </javadoc>
    	  <zip destfile="${build.dist.dir}/${javadocfile}" basedir="${build.dist.dir}/javadoc" />
      </target>

    <target name="publish" depends="jar,javadoc">
	 	<scp file="${build.dist.dir}/${archivefile}"    trust="true" todir="prelle@rpgframework.de:/var/www/html/jar/" keyfile="${user.home}/.ssh/id_rsa" />
	 	<scp file="${build.dist.dir}/${javadocfile}"    trust="true" todir="prelle@rpgframework.de:/var/www/html/javadoc/" keyfile="${user.home}/.ssh/id_rsa" />
	 	<scp file="${build.dist.dir}/${archivefile}"    trust="true" todir="prelle@rpgframework.de:/var/www/html/bootloader1/${repository}/" keyfile="${user.home}/.ssh/id_rsa" />
	 	<scp file="${build.dist.dir}/${archivefile}"    trust="true" todir="prelle@rpgframework.de:/var/www/html/bootloader2.5/${repository}/" keyfile="${user.home}/.ssh/id_rsa" />
	 	<scp file="releasenotes.html" trust="true" todir="prelle@rpgframework.de:/var/www/html/bootloader1/${repository}/${package}.jar.html" keyfile="${user.home}/.ssh/id_rsa" />
	 	<scp file="releasenotes.html" trust="true" todir="prelle@rpgframework.de:/var/www/html/bootloader2.5/${repository}/${package}.jar.html" keyfile="${user.home}/.ssh/id_rsa" />
    	<sshexec host="rpgframework.de" trust="true"
    		username="prelle"
    		keyfile="${user.home}/.ssh/id_rsa"
     		command="unzip -q -o -d /var/www/html/javadoc/${package}-${baseversion} /var/www/html/javadoc/${javadocfile}"/>
    	<!--sshexec host="rpgframework.de" trust="true"
    		username="prelle"
    		keyfile="${user.home}/.ssh/id_rsa"
     		command="cd /var/www/html/bootloader1/${repository}; ln -sf ${archivefile} ${package}.jar"/-->
	</target>

</project>