<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.prelle.rpgframework</groupId>
		<artifactId>splittermond-all</artifactId>
		<version>4.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>splittermond-core</artifactId>

	<name>Splittermond Core</name>
	<description>Data structures for Splittermond</description>

  <properties>
    <maven.deploy.skip>false</maven.deploy.skip>
  </properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-chars</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-products</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>simple-persist</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>javax.mail</artifactId>
			<version>[1.6.0,)</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>

		</plugins>
	</build>
</project>