<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.rpgframework</groupId>
    <artifactId>genesis-root</artifactId>
    <version>3.2</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <groupId>org.prelle.rpgframework</groupId>
  <artifactId>splittermond-zhoujiang</artifactId>
  <version>1.1</version>
  <name>Splittermond 'Zhoujiang'</name>
  
  <organization>
    <name>Nils Dziemballa</name>
  </organization>

  <dependencies>
  	<dependency>
  		<groupId>log4j</groupId>
  		<artifactId>log4j</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>de.rpgframework</groupId>
  		<artifactId>rpgframework-api</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-core</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-msk</artifactId>
  	</dependency>
  	<dependency>
  		<groupId>org.prelle.rpgframework</groupId>
  		<artifactId>splittermond-beastmaster</artifactId>
  	</dependency>
  </dependencies>
</project>