dialog.editcarrieditem.title=Gegenstand verbessern

label.material=Material
label.personalization.first=Personalisierung
label.personalization.second=2. Personalisierung

pane.basic=Grunddaten
pane.weapon=Nahkampf
pane.rangeweapon=Fernkampf
pane.armor=Rüstung
pane.shield=Schild
pane.descr=Beschreibung
pane.other=Sonstiges