dialog.editcarrieditem.title=Bearbeiten: %s

field.name.prompt=z.B. "Glamdring"

label.available=Verfügbare Verbesserungen
label.description=Information
label.material=Material
label.name=Name
label.personalization.first=Personalisierung
label.personalization.second=2. Personalisierung
label.selected=Gewählte Verbesserungen
label.skill=Fertigkeit
label.specialization=Schwerpunkt

pane.basic=Grunddaten
pane.weapon=Nahkampf
pane.rangeweapon=Fernkampf
pane.armor=Rüstung
pane.shield=Schild
pane.descr=Beschreibung
pane.other=Sonstiges

dialog.selectSpecializationEnhancement=Wähle einen Schwerpunkt
dialog.selectSpecializationEnhancement.desc=Wähle einen Schwerpunkt von %s
dialog.selectSpellEnhancement=Wähle einen Zauber
dialog.selectSpellEnhancement.desc=Wähle den im Gegenstand zu verankernden Zauber

enhancements.selected.placeholder=Ziehen Sie gewünschte Verbesserungen per Drag&Drop hier rein

screen.enhancements.embedspell.cell=Strukturgeber '%s'