dialog.masterships.title=Schwerpunkte und Meisterschaften
label.masterships=Meisterschaften
label.available=Verfügbar
label.selected=Gewählt
label.specializations=Schwerpunkte
label.description=Beschreibung
label.ep.free=EP
screen.masterships.master_or_special=Was wollen Sie auswählen?
screen.masterships.descr.spelltype=Der Schwerpunkt kommt in folgenden Zaubern vor
screen.masterships.search=Filtern nach Suchbegriff:

warning.license=Inhaber einer Splittermond-Lizenz sehen hier den Beschreibungstext.