button.select=Auswählen

creature.weapon.item=Waffe
creature.weapon.name=Bezeichnung
creature.weapon.value=Wert

label.type=Art
label.training=Abrichtungen
label.ticks=Ticks
label.1d6=1W6
#label.desc=Beschreibungstext
#label.delete=Löschen
label.masterships=Meisterschaften
label.skills=Fertigkeiten
label.spells=Zauber
label.weapons=Waffen
label.features=Merkmale

section.resource.dialog.add.question=Wählen Sie die Ressource, die sie hinzufügen wollen
section.resource.dialog.add.title=Ressource hinzufügen
section.resource.dialog.add.placeholder=Ich finde Ihren Mangel an Ressourcen beklagenswert!

section.creature.add.add_creature=Kreatur auswählen
section.creature.add.create_creature=Kreatur erstellen
section.creature.add.create_entourage=Gefolge erstellen
section.creatures.addcreaturedialog.title=Wähle eine Kreatur

placeholder.creature.possible=Es stehen keine Kreaturen zur Verfügung
placeholder.creaturemodulereferences.selected=Ziehe die Kreatur-Optionen hier herüber

dialog.creature.create.title=Kreatur erschaffen
dialog.creature.create.cost=Kreatur:
dialog.creature.create.type=Typus
dialog.creature.create.base=Basis
dialog.creature.create.role=Rolle
dialog.creature.create.typedialog.title=Kreatur-Typus auswählen
dialog.creature.train.title=Kreatur abrichten
dialog.creature.train.pointspane.left=Abrichtungspunkte zu vergeben
dialog.creature.train.pointspane.descr=Wählen Sie die gewünschten Abrichtungen via Drag and Drop. Das gilt auch für das Abwählen.\n\nSollten Bedingungen für eine Abrichtung nicht erfüllt sein, wird dies in rotem Text angegeben.
dialog.creature.add.add_creature=Wahl aus Liste
dialog.creature.add.create_creature=Tier erschaffen
dialog.creature.add.create_entourage=Gefolge hinzufügen
dialog.creatures.namedialog.mess=Wie heisst der Begleiter?
dialog.creatures.namedialog.title=Name wählen
