section.culturelores.dialog.add.question=Wählen Sie eine Kulturkunde, die sie erlernen wollen.
section.culturelores.dialog.add.title=Kulturkunde wählen
section.culturelores.dialog.add.placeholder=Nichts wählbar.\nEvtl. fehlen EP?
section.culturelores.dialog.add.uncommon=Auch Kulturkunden anzeigen, bei denen die Sprache nicht beherrscht wird.