label.birthplace=Geburtsort
label.deity=Gottheit
label.hair=Haarfarbe
label.eyes=Augenfarbe
label.size=Größe
label.skin=Hautfarbe
label.weight=Gewicht

button.add.tooltip=Portrait setzen
button.delete.tooltip=Portrait löschen