section.power.dialog.add.question=Wählen Sie die Stärke, die sie hinzufügen wollen
section.power.dialog.add.title=Stärke hinzufügen
section.power.dialog.add.placeholder=Sie brauchen mindestens 7 EP/1 GP für eine neue Stärke