section.resource.dialog.add.question=Wählen Sie die Ressource, die sie hinzufügen wollen
section.resource.dialog.add.title=Ressource hinzufügen
section.resource.dialog.add.placeholder=Ich finde Ihren Mangel an Ressourcen beklagenswert!

section.resource.dialog.settings.title=Einstellungen zu Ressourcen
section.resource.dialog.settings.cbAllow=Mein Spielleiter erlaubt außergewöhnliche Ressourcen 

listcell.resourceref.relicdialog.title=Wählen Sie einen Gegenstand aus
listcell.resourceref.relicdialog.descr=Was wollen Sie tun?
listcell.resourceref.relicdialog.cell=Q%d: %s
listcell.resourceref.relicdialog.option1=Ich möchte ein vorhandenen Gegenstand der Qualität %d mit der Ressource "Relikt %d" verknüpfen.
listcell.resourceref.relicdialog.option2=Ich möchte ein vorhandenen Gegenstand beliebiger Qualität mit der Ressource "Relikt %d" aufwerten.
listcell.resourceref.relicdialog.option3=Ich möchte ein neuen Gegenstand der Qualität %d als "Relikt %d" hinzufügen.
listcell.resourceref.relicdialog.placeholder=Kein passender Gegenstand vorhanden

listcell.resourceref.namedialog.title=Geben Sie der Ressource einen Namen
