section.resource.dialog.add.question=Wählen Sie die Ressource, die sie hinzufügen wollen
section.resource.dialog.add.title=Ressource hinzufügen
section.resource.dialog.add.placeholder=Ich finde Ihren Mangel an Ressourcen beklagenswert!