<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.prelle.rpgframework</groupId>
    <artifactId>splittermond-all</artifactId>
	<version>4.0.1-SNAPSHOT</version>
  </parent>

	<artifactId>splittermond-chargen-jfx</artifactId>

	<name>Splittermond_CharGen_JFX</name>
	<description>GUI classes for the Splittermond Character Generator</description>

  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-core</artifactId>
		</dependency>
    <dependency>
      <groupId>org.prelle</groupId>
      <artifactId>simple-persist</artifactId>
    </dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle.rpgframework</groupId>
			<artifactId>splittermond-chargen</artifactId>
		</dependency>
		<dependency>
			<groupId>org.prelle</groupId>
			<artifactId>javafx-extensions</artifactId>
		</dependency>
		<dependency>
			<groupId>de.rpgframework</groupId>
			<artifactId>rpgframework-javafx</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
      <version>4.12</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
